[WIP] monitoring super container
livepeer/docker-livepeer pull request #12
Opened 2020-01-09 16:45 UTC by ya7ya

This container will include all the required services we need to run monitoring in various cloud providers and standalone setups.

fixes https://github.com/livepeer/go-livepeer/issues/1274

2020-01-09 19:24 UTC, iameli requested changes

2020-01-09 19:24 UTC, iameli commented on monitoring/Dockerfile
> +COPY --from=c1 /lib64 /lib64
This kind of thing makes me nervous — are we going to step on any libraries added by any of the other dependencies? Are the naming conventions going to be consistent?

I'd be more inclined to start with a vanilla ubuntu or debian container and install Prometheus/Grafana/Phantom with a package manager — it's only a marginal increase in image size but is a lot easier to reason about.

2020-01-09 19:24 UTC, iameli commented on monitoring/supervisord.conf
> +[program:prometheus]
Check this example for logging — the `/dev/fd/1` trick here seems to work well for getting stdout on the container. https://github.com/livepeer/livepeer-wowza/blob/master/etc/WowzaStreamingEngine.conf

2020-01-23 18:30 UTC, ya7ya commented
How to build the container for testing this PR
```bash
# in  docker-livepeer/monitoring 
$ sudo docker build -t super-container:latest -f Dockerfile .

# standalone mode listening to 2 livepeer nodes at 7935 and 7936 locally
$ sudo docker run --rm --name=monitoring --net=host --env LP_MODE=standalone --env LP_NODES=localhost:9735,localhost:7936 super-container:latest

# kubernetes with a namespace(s)
$ sudo docker run --rm --name=monitoring --net=host --env LP_MODE=kubernetes --env LP_KUBE_NAMESPACES=default,kube-system super-container:latest

```
 to see the generated `prometheus.yml`, simply `sudo docker exec -it monitoring cat /etc/prometheus/prometheus.yml` :+1:

2020-01-24 09:03 UTC, iameli requested changes
Looks solid! Just a few line-by-line things.

I have one suggestion that I think would make this a lot easier to use: let's handle environment variable/CLI parsing with `yargs`, such that the following two commands would work the same way:

```
docker run --env LP_MODE=standalone --env LP_NODES=localhost:9735,localhost:7936 livepeer/monitor
```

and

```
docker run livepeer/monitor --mode=standalone --nodes=localhost:9735,localhost:7936
```

I think the latter is easier to read and reason about. It also gives us a good place to put documentation; that's as easy as `docker run livepeer/monitor --help`, where we can explain all the usage information and caveats (`--net=host`) and whatnot.

I don't think this should be too hard to implement, you can copy the same pattern I used on the API here: https://github.com/livepeer/livepeerjs/blob/master/packages/api/src/cli.js#L21

Sorry for the last minute feature request! Totally okay to get this merged with the other changes first and open a new branch if you'd like to do it that way.

2020-01-24 09:04 UTC, iameli commented
Would also be nice to get this into a CI pipeline so changes are pushed automatically. Take your pick, I think company-wide we're using like... six

2020-01-24 09:06 UTC, iameli commented on monitoring/start.sh
> +node /config-generator/src/generate.js
For yargs, we can pass in incoming CLI requests with... I think `node /config-generator/src/generate.js "$@"`. But maybe `$*` or `"$*"` or `$@` would work better, I can never keep track of those four

2020-01-27 17:34 UTC, ya7ya commented on monitoring/config-generator/src/generate.js
> +  console.log(process.env)
yeah i'm gonna clean up all these console logs :+1:

2020-01-27 22:10 UTC, iameli approved these changes
LGTM! Let's write some documentation for `--help` and merge this during our 1-on-1 tomorrow.

2020-01-28 19:03 UTC, merged